name: docs-dev

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0  # fetch all commits
          fetch-tags: true
      - uses: actions/setup-python@v5
      - name: get tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          for tag in $(git tag | grep -E v\[0-9]+.\[0-9]+.\[0-9]+$); git checkout -b $tag refs/tags/${tag} && if [ -d "./docs" ]; then rm -r ./docs; fi && pip install .[docs] && sphinx-build -b html ./docs_src ./docs/${tag} && git add docs && git commit -m "build docs by bot" && git checkout main && git checkout --force ${tag} -- docs; done
          git checkout main
          pip install -e .[docs]
          sphinx-build -b html ./docs_src ./docs/main
          git commit -am "build docs by bot"
          git push origin main


      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v4
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./docs
      #     force_orphan: true
