name: docs

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0  # fetch all commits
          fetch-tags: true
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip install -e .[docs]
      - name: Add path
        run: |
          echo "$(pwd)" >> $GITHUB_PATH && ls
      - name: Sphinx build
        run: |
          sphinx-multiversion ./docs_src ./docs
      - name: Commit docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add docs
          git commit -m "build docs by bot"
          git push origin main
      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v4
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./docs
      #     force_orphan: true
