name: docs

on:
  workflow_dispatch:
#   push:
#     branches:
#       - 'main'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: joutvhu/get-release@v1
        with:
          pattern: '^v.*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
